use BM303_2223G_VT001;

go
CREATE TABLE DDEPENDENT (
Essn VARCHAR(32) NOT NULL,
Dependent_name VARCHAR(32) NOT NULL,
Sex VARCHAR(32),
Bdate DATE,
Relationship VARCHAR(32),
PRIMARY KEY (Essn, Dependent_name));

go
CREATE TABLE DEPARTMENT (
Dname VARCHAR(32) NOT NULL,
Dnumber INT NOT NULL,
Mgr_ssn VARCHAR(32) NOT NULL,
Mgr_start_date DATE,
PRIMARY KEY (Dnumber), UNIQUE (Dname));

go
CREATE TABLE DEPT_LOCATIONS (
Dnumber INT NOT NULL,
Dlocation VARCHAR(32) NOT NULL,
PRIMARY KEY (Dnumber, Dlocation));

go
CREATE TABLE EMPLOYEE (
Fname VARCHAR(32) NOT NULL,
Minit VARCHAR(32),
Lname VARCHAR(32) NOT NULL,
Ssn VARCHAR(32) NOT NULL,
Bdate DATE,
Addressx VARCHAR(32),
Sex VARCHAR(32),
Salary DECIMAL(10,2),
Super_ssn VARCHAR(32),
Dno INT NOT NULL,
PRIMARY KEY (Ssn));

go
CREATE TABLE PROJECT (
Pname VARCHAR(32) NOT NULL,
Pnumber INT NOT NULL,
Plocation VARCHAR(32),
Dnum INT NOT NULL,
PRIMARY KEY (Pnumber),
UNIQUE (Pname));

go
CREATE TABLE WORKS_ON (
Essn VARCHAR(32) NOT NULL,
Pno INT NOT NULL,
Hours DECIMAL(10,2) NOT NULL,
PRIMARY KEY (Essn, Pno));